X = float(input("Konfetning umumiy qiymatini kiriting(X): "))
A = float(input("Konfetning summasini kiriting: "))
Y = float(input("Qancha konfet uchun summa hisoblamoqchisiz: "))
print("Bir kg uchun narx:",A/X)
print("Y kg uchun narx:",Y*A/X)
